- name: Instalando rsyslog
  ansible.builtin.apt:
    name: rsyslog
    state: latest

- name: Habilitando rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: started
    enabled: yes

- name: Instalando ufw
  ansible.builtin.apt:
    name: ufw
    state: latest

- name: Permitir el acceso al servicio SSH
  ansible.builtin.ufw:
    rule: limit
    port: "22"
    proto: tcp

- name: Habilitar ufw
  ansible.builtin.ufw:
    state: enabled
    policy: deny

- name: Habilitar el log
  ansible.builtin.ufw:
    logging: medium

- name: Configuramos la rotacion de las bitacoras de ufw
  ansible.builtin.template:
    src: ufw.j2
    dest: /etc/logrotate.d/ufw
    owner: root
    group: root
    mode: '0644'
