- name: Instalar HIPS
  ansible.builtin.apt:
    name:
      - fail2ban
    state: present

- name: Copiamos una configuracion personalizada
  ansible.builtin.copy:
    src: "jail.local"
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify: restart_fail2ban
