- name: Copy template of debian.sources config file
  ansible.builtin.template:
    src: debian.sources.j2
    dest: /etc/apt/sources.list.d/debian.sources
    owner: root
    group: root
    mode: '0644'

- name: Copy template of APT config file
  ansible.builtin.template:
    src: apt.conf.j2
    dest: /etc/apt/apt.conf
    owner: root
    group: root
    mode: '0644'
