- name: Install postfix
  ansible.builtin.apt:
    name:
      - postfix
    state: present

- name: Your domain name
  ansible.builtin.lineinfile:
    dest: /etc/postfix/main.cf
    regexp: "^mydomain ="
    line: 'mydomain = {{ MAIL_DOMAIN }}'
  notify: restart_postfix

- name: The name of your mail server
  ansible.builtin.lineinfile:
    dest: /etc/postfix/main.cf
    regexp: "^myhostname ="
    line: 'myhostname = {{ MAIL_NAME }}.$mydomain'
  notify: restart_postfix

- name: domain name that will appear in the "From" address
  ansible.builtin.lineinfile:
    dest: /etc/postfix/main.cf
    regexp: "^myorigin ="
    line: 'myorigin = $mydomain'
  notify: restart_postfix

- name: Specifies which interfaces Postfx listen
  ansible.builtin.lineinfile:
    dest: /etc/postfix/main.cf
    regexp: "^inet_interfaces ="
    line: 'inet_interfaces = all'
  notify: restart_postfix

- name: Specifies which protocols Postfx listen
  ansible.builtin.lineinfile:
    dest: /etc/postfix/main.cf
    regexp: "^inet_protocols ="
    line: 'inet_protocols = all'
  notify: restart_postfix

- name: Enable logs for postfix
  ansible.builtin.lineinfile:
    dest: /etc/postfix/main.cf
    regexp: "^maillog_file ="
    line: 'maillog_file = /var/log/mail.log'
  notify: restart_postfix

- name: Configuramos la rotacion de bitacoras
  ansible.builtin.template:
    src: postfix.j2
    dest: /etc/logrotate.d/postfix
  notify: restart_postfix

- name: Install postfix Auth library
  ansible.builtin.apt:
    name:
      - libsasl2-modules
    state: present

- name: copy gmail configurations
  ansible.builtin.copy:
    src: "sasl_passwd"
    dest: /etc/postfix/sasl/sasl_passwd
    owner: root
    group: root
    mode: '0600'
  notify: restart_postfix

- name: copy gmail configurations db
  ansible.builtin.copy:
    src: "sasl_passwd.db"
    dest: /etc/postfix/sasl/sasl_passwd.db
    owner: root
    group: root
    mode: '0600'
  notify: restart_postfix

- name: Enable Auth Service for Client Using Dovecot (1 de 5)
  ansible.builtin.lineinfile:
    dest: /etc/postfix/main.cf
    regexp: "^relayhost ="
    line: 'relayhost = [smtp.gmail.com]:587'
  notify: restart_postfix

- name: Enable Auth Service for Client Using Dovecot (1 de 5)
  ansible.builtin.lineinfile:
    dest: /etc/postfix/main.cf
    regexp: "^smtp_sasl_auth_enable ="
    line: 'smtp_sasl_auth_enable = yes'
  notify: restart_postfix

- name: Enable Auth Service for Client Using Dovecot (4 de 5)
  ansible.builtin.lineinfile:
    dest: /etc/postfix/main.cf
    regexp: "^smtp_sasl_security_options ="
    line: 'smtp_sasl_security_options = noanonymous'
  notify: restart_postfix

- name: Enable Auth Service for Client Using Dovecot (4 de 5)
  ansible.builtin.lineinfile:
    dest: /etc/postfix/main.cf
    regexp: "^smtp_sasl_password_maps ="
    line: 'smtp_sasl_password_maps = hash:/etc/postfix/sasl/sasl_passwd'
  notify: restart_postfix

- name: Enable use TLS between servers (2 de 3)
  ansible.builtin.lineinfile:
    dest: /etc/postfix/main.cf
    regexp: "^smtp_tls_security_level ="
    line: 'smtp_tls_security_level = encrypt'
  notify: restart_postfix

- name: Enable use TLS between servers (2 de 3)
  ansible.builtin.lineinfile:
    dest: /etc/postfix/main.cf
    regexp: "^smtp_tls_CAfile ="
    line: 'smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt'
  notify: restart_postfix

